config/routes.rb
Rails.application.routes.draw do

  get 'collaborators/index'

  get 'collaborators/new'

  devise_for :users
  resources :users, only: [:update]
  resources :wikis
  resources :charges, :users

  get 'welcome/index'

  get 'welcome/about'

    root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable

  def payment
    customer = Stripe::Customer.create(:card => token,:description => "avyishi@yahoo.com")
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  require 'librato/metrics'
  Librato::Metrics.authenticate 'avyishi@gmail.com', '43a3a9d32f4ddf20ad5ca01db38e270c861448701f08834afb66ce963cd09fc1'
  Librato::Metrics.submit :my_metric => 42, :my_other_metric => 1002
  
  belongs_to :user
  has_many :users


  default_scope { order('created_at DESC') }

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  #def should_generate_new_friendly_id?
   # new_record?
  #end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
       @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        description: 'Premium Plan',
        amount: 9
      }
    end


    def create
    # Amount in cents
    @amount = 999
    # @amount = 500

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer:  customer.id,
      amount:    @amount,
      description: 'Premium Customer',
      currency: 'usd'
    )

    current_user.update_attribute(:premium, true)

      redirect_to wikis_path, flash: {notice: 
        "Thank you for subscribing! You're ready to create wikis."}

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

  before_filter :require_login

  private

    def require_login
      unless current_user
        redirect_to edit_user_registration_path
      end
    end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
 
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       render "devise/registrations/edit"
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name)
   end
   
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
    @wikis = current_user.wikis.paginate(page: params[:page], per_page: 10)



  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    @wikis = current_user.wikis.paginate(page: params[:page], per_page: 10)

    if request.path != wiki_path(@wiki)
      redirect_to @wiki, status: :moved_permanently
      end
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)
      if @wiki.save
      flash[:notice] = "Awesome, wiki was created successfully!"
      redirect_to @wiki
    else
      flash[:error] = "There was an error creating the wiki. Please try again"
      render :new
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])
    name = @wiki.name
      if @wiki.destroy
       flash[:notice] = "\"#{name}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash[:error] = "There was an error deleting the wiki."
       render :show
     end


  end


  def edit
    @wiki = Wiki.friendly.find(params[:id])
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
      else
       flash[:error] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  private 

  def wiki_params
    params.require(:wiki).permit(:name, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$9.99</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $9.99</span>
    </label>
  </article>

<h2>Click to upgrade!</h2>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="999"></script>
<% end %>

app/views/collaborators/index.html.erb
<h1>Collaborators#index</h1>
<p>Find me in app/views/collaborators/index.html.erb</p>

app/views/collaborators/new.html.erb
<h1>Collaborators#new</h1>
<p>Find me in app/views/collaborators/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chepedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
        <li><%= link_to "Chepedia", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>

        <div class="pull-right user-info">
           <% if current_user %>
             Hey <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
         
   </ul>

   <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>

    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>

    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>

    <% end %>

<%= yield %>
</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
table {
    width:100%;
}
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 4px;
    text-align: left;
}
table#t01 tr:nth-child(even) {
    background-color: #fff;
}
table#t01 tr:nth-child(odd) {
   background-color:#fff;
}
table#t01 th  {
    background-color: black;
    color: white;
}
</style>
</head>

<body>

<table style = "width:100%" id="t01">
  <caption><h3>All Users</h3></caption>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>

    <tr>
      <% User.all.each do |user| %>
        <td>
        <%= user.name %>
        </td>
        <td>
        <%= user.email%>
        </td>
    </tr>
    <% yield %>
    <% end %> 
</table>

</br>

</body>
</html>
<%=link_to "Back to Edit", :back %>

app/views/welcome/about.html.erb
<h1>Wikis by Chepedia</h1>
<p>Created by: Chéri</p>

app/views/welcome/index.html.erb
<div class="jumbotron" id="welcome">
  <h1 align= "center">Chepedia</h1>
  <p align= "center">Chepedia: Social, Markdown Wikis</p>
  <p align= "center">Create and share Markdown Wikis</p>
  <p align= "center">
  <%- if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary :hover'  %>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
  </p>
</div>

<div class="row" >
  <div class="col-md-4">
    <h2 align = "center">Create as many public wikis as you want!</h2>
    <p align = "center"><%= link_to "Free Plan", new_user_registration_path, class: 'btn btn-primary' %></p>
  </div>

  <div class="col-md-4">
    <h2 align = "center">Create private wikis for $9.99!</h2>

  <p align = "center"><%= link_to "Premium Upgrade", new_charge_path(premium: true), class: 'btn btn-primary' %></p>
  
    
  </div>
</div>

app/views/wikis/_form.html.erb
<div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter wiki name" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
        <%= f.check_box :public %> Public wiki
        <% end %>
      </div>
        <%= f.submit "Save", class: 'btn btn-success' %>
        <%= link_to "Cancel", wikis_path, class: 'btn btn-warning' %>
    <% end %>
</div>

app/views/wikis/edit.html.erb
<h1>Edit <%= @wiki.name %></h1>

<div class="row">

  <div class="col-md-8">
    <%= render partial: 'form' %> 
  </div>
</div>
<div class="col-md-8">
  
  

app/views/wikis/index.html.erb
<h1>All The Wikis</h1>
<p><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %></p>

<table style = "width:100%">
  <tr>
    <td><% @wikis.each do |wiki| %></td>
  </tr>

  <tr>
    <td>
      <div class="media">
      <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.name, wiki_path(wiki) %>
      </h4>
      <small>
        created <%= time_ago_in_words(wiki.created_at) %> by <%= wiki.user.name %>
      </small>
    </td>
  </tr>
      </div>
      </div>
      <% end %>
</table>

<%= will_paginate @wikis %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Blah Wiki Blah</p>
    <ul>
    
    </ul>
  </div>
    <%= render partial: 'form' %> 
</div>

app/views/wikis/show.html.erb
<div class="col-md-4">
  <h1><%= markdown @wiki.name %></h1>
  
    <%= link_to "Edit", edit_wiki_path, class: 'btn btn-success' %>

    <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 

    <%= link_to "Cancel", wikis_path, class: 'btn btn-warning' %>
</div>